In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
},
    index=[0, 1, 2])

In [7]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [17]:
df.loc[0,'a':'b']

a    1
b    4
Name: 0, dtype: int64

In [24]:
df.iloc[0,0]

np.int64(1)

In [25]:
df.iloc[0,0]=5

In [26]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [31]:
df.iloc[0, 0]

np.int64(5)

In [32]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [33]:
df.sum()

a    10
b    15
c    24
dtype: int64

In [34]:
df.min()

a    2
b    4
c    7
dtype: int64

In [35]:
df.max()

a    5
b    6
c    9
dtype: int64

In [37]:
df['a'].value_counts()

a
5    1
2    1
3    1
Name: count, dtype: int64

In [38]:
df['a'].nunique()

3

In [39]:
df.describe()

              a    b    c
count  3.000000  3.0  3.0
mean   3.333333  5.0  8.0
std    1.527525  1.0  1.0
min    2.000000  4.0  7.0
25%    2.500000  4.5  7.5
50%    3.000000  5.0  8.0
75%    4.000000  5.5  8.5
max    5.000000  6.0  9.0

In [41]:
df.head(2)

   a  b  c
0  5  4  7
1  2  5  8

In [42]:
df.tail(2)

   a  b  c
1  2  5  8
2  3  6  9

In [43]:
df.sample(2)

   a  b  c
0  5  4  7
1  2  5  8

In [44]:
df.isnull()

       a      b      c
0  False  False  False
1  False  False  False
2  False  False  False

In [45]:
df.isnull().sum()

a    0
b    0
c    0
dtype: int64

In [46]:
df.mean()

a    3.333333
b    5.000000
c    8.000000
dtype: float64

In [47]:
df.median()

a    3.0
b    5.0
c    8.0
dtype: float64

In [48]:
df.quantile()

a    3.0
b    5.0
c    8.0
Name: 0.5, dtype: float64

In [49]:
df.groupby('a').mean()

     b    c
a
2  5.0  8.0
3  6.0  9.0
5  4.0  7.0

In [50]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [55]:
df.groupby(level=0).mean()

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  8.0
2  3.0  6.0  9.0

In [56]:
df.shift(1)

     a    b    c
0  NaN  NaN  NaN
1  5.0  4.0  7.0
2  2.0  5.0  8.0

In [59]:
df.shift(2)

     a    b    c
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  5.0  4.0  7.0

In [60]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [61]:
df.max()

a    5
b    6
c    9
dtype: int64