In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
},
    index=[0, 1, 2])

In [3]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [4]:
df.loc[0,'a':'b']

a    1
b    4
Name: 0, dtype: int64

In [5]:
df.iloc[0,0]

np.int64(1)

In [6]:
df.iloc[0,0]=5

In [7]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [8]:
df.iloc[0, 0]

np.int64(5)

In [9]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [10]:
df.sum()

a    10
b    15
c    24
dtype: int64

In [11]:
df.min()

a    2
b    4
c    7
dtype: int64

In [12]:
df.max()

a    5
b    6
c    9
dtype: int64

In [13]:
df['a'].value_counts()

a
5    1
2    1
3    1
Name: count, dtype: int64

In [14]:
df['a'].nunique()

3

In [15]:
df.describe()

              a    b    c
count  3.000000  3.0  3.0
mean   3.333333  5.0  8.0
std    1.527525  1.0  1.0
min    2.000000  4.0  7.0
25%    2.500000  4.5  7.5
50%    3.000000  5.0  8.0
75%    4.000000  5.5  8.5
max    5.000000  6.0  9.0

In [16]:
df.head(2)

   a  b  c
0  5  4  7
1  2  5  8

In [17]:
df.tail(2)

   a  b  c
1  2  5  8
2  3  6  9

In [18]:
df.sample(2)

   a  b  c
0  5  4  7
2  3  6  9

In [19]:
df.isnull()

       a      b      c
0  False  False  False
1  False  False  False
2  False  False  False

In [20]:
df.isnull().sum()

a    0
b    0
c    0
dtype: int64

In [21]:
df.mean()

a    3.333333
b    5.000000
c    8.000000
dtype: float64

In [22]:
df.median()

a    3.0
b    5.0
c    8.0
dtype: float64

In [23]:
df.quantile()

a    3.0
b    5.0
c    8.0
Name: 0.5, dtype: float64

In [24]:
df.groupby('a').mean()

     b    c
a
2  5.0  8.0
3  6.0  9.0
5  4.0  7.0

In [25]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [26]:
df.groupby(level=0).mean()

     a    b    c
0  5.0  4.0  7.0
1  2.0  5.0  8.0
2  3.0  6.0  9.0

In [27]:
df.shift(1)

     a    b    c
0  NaN  NaN  NaN
1  5.0  4.0  7.0
2  2.0  5.0  8.0

In [28]:
df.shift(2)

     a    b    c
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  5.0  4.0  7.0

In [29]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [30]:
df.max()

a    5
b    6
c    9
dtype: int64

In [31]:
df.min()

a    2
b    4
c    7
dtype: int64

In [32]:
df1=pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
},
    index=[0, 1, 2])

In [33]:
df1

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [34]:
df+df1

   a   b   c
0  6   8  14
1  4  10  16
2  6  12  18

In [35]:
df.merge(df1, on='a')

   a  b_x  c_x  b_y  c_y
0  2    5    8    5    8
1  3    6    9    6    9

In [36]:
df.merge(df1, on='b',how='left')

   a_x  b  c_x  a_y  c_y
0    5  4    7    1    7
1    2  5    8    2    8
2    3  6    9    3    9

In [37]:
df.merge(df1, on='c',how='right')

   a_x  b_x  c  a_y  b_y
0    5    4  7    1    4
1    2    5  8    2    5
2    3    6  9    3    6

In [38]:
df.merge(df1, on='c',how='inner')

   a_x  b_x  c  a_y  b_y
0    5    4  7    1    4
1    2    5  8    2    5
2    3    6  9    3    6

In [39]:
pd.concat([df, df1])

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9
0  1  4  7
1  2  5  8
2  3  6  9

In [40]:
pd.concat([df, df1], axis=1)

   a  b  c  a  b  c
0  5  4  7  1  4  7
1  2  5  8  2  5  8
2  3  6  9  3  6  9

In [42]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9